### ISSUE TITLE
Redirection en boucle sur les groupes non préalablement configurés

### ISSUE THREAD

**Issue by mecanographik** [imath/altctrl-public-group#11]
Salut Mathieu,
J'espère que tu vas bien! j'ai testé ton plugin pour l'utiliser sur [https://www.time2sail.com](https://www.time2sail.com)
J'ai trouvé un bug et j'ai appliqué une solution. Lorsque tu es connecté en front, en utilisateur lambda (non admin) et que tu souhaites accéder à un groupe public depuis l'annuaire des groupes, si les options de ton plugin n'ont pas été réglées préalablement pour ce groupe, alors je ne peux pas accéder au groupe à cause d'une redirection sans fin. La raison est que la groupmeta '_altctrl_tabs' n'a pas encore été enregistrée en bdd une première fois à priori...
Pour palier à ce bug et ne pas déclencher 'bp_core_redirect' et permettre à l'utilisateur non membre d'accéder au groupe en question, j'ai modifié le fichier : includes/alt-public-group-ctrl.php vers la ligne #133 en ajoutant la condition suivante:

`if (groups_get_groupmeta( $this->group->id, '_altctrl_tabs')) { ... }`

donc le snippet entier devient :

```
// Redirect if trying to access the page
        if (groups_get_groupmeta( $this->group->id, '_altctrl_tabs')) {
            if ( ! empty( $hidden_tabs ) && in_array( bp_current_action(), $hidden_tabs ) ) {
            bp_core_add_message( __( 'This area is restricted to group members', 'altctrl-public-group' ), 'error' );
            bp_core_redirect( bp_get_group_permalink( $this->group ) );
            }
        }
```

 Peut-être trouveras-tu une solution plus simple mais dans mon cas ça fonctionne maintenant.

Merci pour ce plugin, qui je l'espère intégrera un jours le screen 'settings' du composant 'groups' de buddypress!
@+

**Comment by imath** [comment]
Hello,

je vais bien, je vais regarder cela de plus près merci pour ton feedback.

**Comment by imath** [comment]
Je ne suis pas parvenu à reproduire. Tout fonctionne correctement pour moi.
