### ISSUE TITLE
Not working on newest WP and Multisite

### ISSUE THREAD

**Issue by Newbird** [imath/altctrl-public-group#3]
Just installed this on a WP Multisite and I don't see any of the options outlined in the video. Using the newest version of WP and BuddyPress.

**Comment by krafit** [comment]
With current versions of WP (4.1) and BP (2.1.1) settings show up, but group admins don't seem not be able to see nor accept membership requests.

**Comment by imath** [comment]
Thanks a lot for your feedbacks. I'll look at it asap.

**Comment by Newbird** [comment]
Imath, I did end up finding the options but they were located in a different format that what was demonstrated – this could have been due to the theme that was being used.

**Comment by imath** [comment]
Just checked everything was working for me.
