### ISSUE TITLE
Checkbox enabled by default 

### ISSUE THREAD

**Issue by virtualcompany** [imath/altctrl-public-group#5]
Hello imath, I installed the plugin “Alternative Public Group Control”. The checkbox “Users need to submit a request to join group” it is disabled by default. Is it possible that this option is always enabled?

![captura](https://cloud.githubusercontent.com/assets/643599/9443260/63da6be0-4a80-11e5-9c20-421b6ef734dd.JPG)
It is marked, but I have to save changes to take effect.

Can you help me? Thank you!

**Comment by virtualcompany** [comment]
Please @imath , i need your help. Could you help me resolve this problem? Thank you!

**Comment by imath** [comment]
Oops sorry Will check this asap

imath.
http://profiles.wordpress.org/imath/

**Comment by virtualcompany** [comment]
Thanks @imath i appreciate it. :)

**Comment by imath** [comment]
Ok, so you'll simply need to add this code to your bp-custom.php file or the functions.php file of your active theme : 

```php
add_filter( 'alt_public_group_ctrl_users_request', '__return_true' );
```
